# Use tall and fullscreen layouts
layouts:
  #  - tall
  - fullscreen
  #  - tall-right
  #  - wide
  #  - two-pane
  #  - 3column-left
  #  - middle-wide
  #  - 3column-right
  #  - 4column-left
  #  - 4column-right
  - column
  - row
  - floating
  #  - widescreen-tall
  #  - widescreen-tall-right
  #  - bsp

  # Keep default mods
mod1:
  - option
  - shift
  #  - command
mod2:
  - option
  - shift
  - control
  #  - command

# Modify the amethyst relaunch to use x and not z
relaunch-amethyst:
  mod: mod2
  key: x

  # Enable focus-follows-mouse
#mouse-follows-focus: false
focus-follows-mouse: true

# Add 10px margin between windows
window-margins: true
window-margin-size: 10

#Amethyst uses two modifier combinations (`mod1` and `mod2`) and can optionally use another two (`mod3` and `mod4`).
#
#| Default Shortcut | Description |
#|---|---|
#| `mod1` | `option + shift` |
#| `mod2` | `ctrl + option + shift` |
#| `mod3` | not defined by default |
#| `mod4` | not defined by default |
#
#And defines the following commands, mostly a mapping to xmonad key combinations.
#
#| Default Shortcut | Description |
#|---|---|
#| `mod1 + space` | Cycle layout forward |
#| `mod2 + space` | Cycle layout backwards |
#| `mod1 + h` | Shrink the main pane |
#| `mod1 + l` | Expand the main pane |
#| `mod1 + ,` | Increase main pane count |
#| `mod1 + .` | Decrease main pane count |
#| `mod1 + j` | Move focus counter clockwise |
#| `mod1 + k` | Move focus clockwise |
#| `mod1 + p` | Move focus to counter clockwise screen |
#| `mod1 + n` | Move focus to clockwise screen |
#| `mod2 + h` | Swap focused window to counter clockwise screen |
#| `mod2 + l` | Swap focused window to clockwise screen |
#| `mod2 + j` | Swap focused window counter clockwise |
#| `mod2 + k` | Swap focused window clockwise |
#| `mod1 + enter` | Swap focused window with main window |
#| `mod1 + z` | Force windows to be reevaluated |
#| `mod2 + z` | Relaunch Amethyst |
#| `mod2 + left` | Throw focused window to space left |
#| `mod2 + right` | Throw focused window to space right |
#| `mod2 + 1` | Throw focused window to space 1 |
#| `mod2 + 2` | Throw focused window to space 2 |
#| `mod2 + 3` | Throw focused window to space 3 |
#| `mod2 + 4` | Throw focused window to space 4 |
#| `mod2 + 5` | Throw focused window to space 5 |
#| `mod2 + 6` | Throw focused window to space 6 |
#| `mod2 + 7` | Throw focused window to space 7 |
#| `mod2 + 8` | Throw focused window to space 8 |
#| `mod2 + 9` | Throw focused window to space 9 |
#| `mod2 + 0` | Throw focused window to space 10 |
#| `none`     | Throw focused window to space 11 |
#| `none`     | Throw focused window to space 12 |
#| `mod1 + w` | Focus Screen 1 |
#| `mod2 + w` | Throw focused window to screen 1 |
#| `mod1 + e` | Focus Screen 2 |
#| `mod2 + e` | Throw focused window to screen 2 |
#| `mod1 + r` | Focus Screen 3 |
#| `mod2 + r` | Throw focused window to screen 3 |
#| `mod1 + q` | Focus Screen 4 |
#| `mod2 + q` | Throw focused window to screen 4 |
#| `mod1 + t` | Toggle float for focused window |
#| `mod1 + i` | Display current layout |
#| `mod2 + t` | Toggle global tiling |
#| `mod1 + a` | Select tall layout |
#| `none` | Select tall-right layout |
#| `mod1 + s` | Select wide layout |
#| `none` | Select middle-wide layout |
#| `mod1 + d` | Select fullscreen layout |
#| `mod1 + f` | Select column layout |
#| `none` | Select row layout |
#| `none` | Select floating layout |
#| `none` | Select widescreen-tall layout |
#| `none` | Select bsp layout |
