[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x666666"
blue = "0xb7cbf4"
cyan = "0xa9c1de"
green = "0xd8fa3b"
magenta = "0xb77ee0"
red = "0xff0000"
white = "0xeeeeee"
yellow = "0xe7c547"

[colors.normal]
black = "0x282828"
blue = "0x91aadf"
cyan = "0xb7cbf4"
green = "0x57ba37"
magenta = "0xcf73e6"
red = "0xd71a1a"
white = "0xdedede"
yellow = "0xf0d50c"

[colors.primary]
background = "0x121212"
foreground = "0xd0d0d0"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "Comic Code Ligatures"
style = "Bold"

[font.bold_italic]
family = "Comic Code Ligatures"
style = "Bold Italic"

[font.italic]
family = "Comic Code Ligatures"

style = "Italic"

[font.normal]
family = "Comic Code Ligatures"
style = "Regular"

[font.offset]
x = 0
y = 1

[keyboard]
bindings = [
	{ key = "Key1",     mods = "Command",       chars = "\u00021" }, # tmux tab 1
	{ key = "Key2",     mods = "Command",       chars = "\u00022" }, # tmux tab 2
	{ key = "Key3",     mods = "Command",       chars = "\u00023" }, # tmux tab 3
	{ key = "Key4",     mods = "Command",       chars = "\u00024" }, # tmux tab 4
	{ key = "T",       mods = "Command",       chars = "\u0002c" }, # tmux new tab 
	{ key = "W",       mods = "Command",       chars = "\u0002x" }, # tmux close tab 
	{ key = "H",       mods = "Command|Shift",       chars = "\u0002p" }, # tmux previous tab RBracket and RBracket seem to currently be broken 
	{ key = "L",       mods = "Command|Shift",       chars = "\u0002n" }, # tmux next tab 
]
[mouse]
hide_when_typing = true

[scrolling]
history = 5000

[shell]
program = "/usr/local/bin/fish"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.9
option_as_alt = "Both"
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
